name: Update snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 1 * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
